; Payload Schema for the FLAG_STARDOME_PROOF Stardome merkle proof request computed by the Stardome modules
; Version 2.0.0

;
; Request payload to compute a Merkle proof for a single leaf.
; The requester provides the Merkle tree (as defined in stardome-merkle-tree.cddl)
; and the leaf index (0-based, leaf-layer index).
;
; -----------------------------------------------------------------------------
; 1. Payload structure
; -----------------------------------------------------------------------------

proof_request_payload = {
  1: bstr,  ; merkle-tree-cbor
  2: uint   ; leaf_index 
}


; where:
;
; merkle-tree-cbor is the Merkle tree to compute the proof on
;
; leaf_index is a 0-based index for the leaf layer