; Payload Schema for the FLAG_STARDOME_ATTESTATION Stardome attestation request
; Version 2.0.0
; This schema defines the CBOR structure of the request payload sent by the host device to the Stardome modules
; to request a Stardome attestation.

; -----------------------------------------------------------------------------
; 1. Payload structure
; -----------------------------------------------------------------------------

stardome_attestation_request = {
  1: bstr,      ; epoch
  2: bstr,      ; previous_mark_w_hash
  3: bstr,      ; nonce
  4: bstr,      ; shcap_policy_id
  5: [+ bstr ],	; source_data
  6: bstr,    	; stardome_chain_data
  7: bool,      ; with_leaf_hashes
}

; where:
;
; epoch is the Stardome Epoch, either the previously accepted or the new one, provided as raw bytes
;
;	previous_mark_w_hash is the hash linkage to the previous Stardome Mark drift window;
;
; nonce is a challenge random value 
;
; shcap_policy_id is an identifier of the adopted Stardome Mark computation policy and the SHCAP version;
;
; source_data is an array where the values are the source data to use as values for the leaf nodes, provided as raw bytes.
; The data is mapped to the `leaf_source` leaf slots as defined in the selected Stardome attestation tree schema, starting from the first `leaf_source` index (fixed leaves are device-owned and are not provided by the request).
;
; stardome_chain_data is the hash linkage to another Stardome attestation (Stardome Chain of Custody)
;
; with_leaf_hashes is a boolean value to request to include leaf hashes within the Stardome attestation response.
